swagger: '2.0'
info:
  title: My API Documentation
  description: Documentation for my RESTful API
  version: 1.0.0
host: localhost:3000  # Update with your API's host and port
basePath: /        # Update with your API's base path
schemes:
  - http
  - https
paths:
  /users:
    get:
      summary: Retrieve a list of users
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Create a new user
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        201:
          description: User created successfully
  /users/{id}:
    get:
      summary: Retrieve a specific user by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/User'
    put:
      summary: Update an existing user by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: User updated successfully
    delete:
      summary: Delete a user by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        204:
          description: User deleted successfully
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
